# Generated by Django 3.0.4 on 2020-03-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_apiusers_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estados',
        ),
    ]
